# Generated by Django 3.2.10 on 2022-02-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_information', '0006_auto_20220223_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('mobile_no', models.CharField(blank=True, max_length=14)),
                ('specialization', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
