# Generated by Django 3.2.10 on 2022-01-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='mobile_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile_no',
            field=models.IntegerField(null=True),
        ),
    ]
